### ISSUE TITLE
Other countries NES appears as blank country

### ISSUE THREAD

**Issue by baldwinkl** [SWS-Methodology/tradeValidationTool#8]
In the validation tool, other countries NES is appearing without a name. 
![image](https://user-images.githubusercontent.com/31275016/30159278-5134158e-93c8-11e7-8380-639b0b743a52.png)

**Comment by chrmongeau** [comment]
The issue is that the file with partners names was generated before the 896 area was created. Now, names are assigned automatically in

https://github.com/SWS-Methodology/faoswsTrade/blob/validationToolDataset/modules/trade_validation_cpc/main.R#L476-L481

where the last version of codes/names is available (and, thus, contains 896).
